package com.sicmagroup.gpr.domain.enumeration;

public enum ClaimEventType {
    SAVED,
    AFFECTED,
    SOLUTION_PROPOSED,
    APPROVED,
    REJECTED,
    SATISFIED,
    UNSATISFIED,
    PARTIAL_SATISFIED,
    CLASSED,
    LITIGATION,
    TRANSMITTED,
    CONVERTED,
    MAIL_SENT_AGENT,
    SMS_SENT_AGENT,
    MAIL_SENT_CLIENT,
    SMS_SENT_CLIENT,
    SESSION_STARTED,
    EXTRA_ADDED,
    // --- SLA ---
    SLA_REMINDER,
    SLA_BREACH,
    AUTO_TRANSMITTED,
    SLA_STUCK,
    SLA_REGULATORY_WARNING,
    SLA_REGULATORY_BREACH,
    WAITING_CUSTOMER,
    SLA_RESUMED,
    SLA_JUSTIFIED,
    CONTACT_ATTEMPT,
    CLOSED_UNREACHABLE
}
